#!/bin/sh

if [ ! -f "$(which gyp)" ]; then
    echo "Install gyp at first..."
    sudo apt-get install gyp
fi

if [ $# -gt 0 ]; then
    if [ "$1" = "debug" ]; then
        gyp --depth=. -fninja -dall ./src/all.gyp
    fi
else
    gyp --depth=. -fninja ./src/all.gyp
fi

ninja -C ./out/Default
